name: sample
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+21

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  built_value: ^8.1.4

  #riverpod
  provider: ^6.0.2
  flutter_riverpod: ^1.0.3
  hooks_riverpod: ^1.0.3

  #google
  google_fonts: ^2.3.1
  google_ml_kit: ^0.7.3

  #firebase
  #firebase_core: ^1.12.0
  #firebase_messaging: ^11.2.10
  #firebase_app_installations: ^0.1.0+8
  firebase_storage: ^10.2.7
  firebase_database: ^9.0.6
  firebase_auth: ^3.3.10

  #network:
  http: ^0.13.4
  web_socket_channel: ^2.1.0
  connectivity_plus: ^2.2.1

  #widget
  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  carousel_slider: ^4.0.0
  path_drawing: ^1.0.0
  modal_bottom_sheet: ^2.0.1
  dotted_border: ^2.0.0+2
  flutter_native_splash: ^2.1.1
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0

  #fluttertoast: ^8.0.9
  pull_to_refresh: ^2.0.0


  #utils
  image: ^3.1.3
  permission_handler: ^9.2.0
  shared_preferences: ^2.0.12
  animator: ^3.1.0
  device_info_plus: ^3.2.1
  easy_localization: ^3.0.0
  app_settings: 4.1.1
  image_picker: ^0.8.4+11
  camera: ^0.9.4+16
  email_validator: ^2.0.1
  crypto: ^3.0.1
  jwt_decoder: ^2.0.1
  path_provider: ^2.0.9
  path: ^1.8.0
  flutter_image_compress: ^1.1.0
  gallery_saver: ^2.3.2
  network_info_plus: ^2.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

#dependency_overrides:
#  path: ^1.6.0
#  http: ^0.12.0


flutter_native_splash:
  background_image: "assets/images/splash.png"
  image: assets/images/splash.png
  background_image_dark: "assets/images/splash.png"
  android_12:
  android_gravity: fill_horizontal
  fullscreen: true


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_400.ttf




