name: sample
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  flutter_riverpod: ^1.0.3
  built_value: ^8.1.4
  provider: ^6.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.12
  connectivity_plus: ^2.2.0
  animator: ^3.1.0
  smooth_page_indicator: ^1.0.0+2
  wifi_iot: ^0.3.14
  device_info_plus: ^3.2.1
  easy_localization: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo_text.png
    - assets/images/wifi_anim.gif
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_400.ttf




