name: sample
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
#  flutter_native_splash: ^1.3.3

flutter:
  uses-material-design: true
#  assets:
#    - images/launch_icon.png
#    - images/logo_text.png
#  fonts:
#    - family: Inter
#      fonts:
#        - asset: fonts/inter_400.ttf
#        - asset: fonts/inter_700.ttf




