// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmpCKmueOk1T6U1yGhMM0SvD_ONpafevA',
    appId: '1:527371630974:android:ab14ab53a1d8c1db3d5b2f',
    messagingSenderId: '527371630974',
    projectId: 'eurowindow-a5688',
    databaseURL: 'https://eurowindow-a5688-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eurowindow-a5688.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOFkANoM5AovLnMm8IYZW8DHQUfab3NzQ',
    appId: '1:527371630974:ios:9def028f4b4d30643d5b2f',
    messagingSenderId: '527371630974',
    projectId: 'eurowindow-a5688',
    databaseURL: 'https://eurowindow-a5688-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eurowindow-a5688.appspot.com',
    iosClientId: '527371630974-mkifne4e69shb5amf1lgkipac4cac4t1.apps.googleusercontent.com',
    iosBundleId: 'wee.dev.ewa',
  );
}
